"""empty message

Revision ID: 037db101b7d5
Revises: c720167ec7a8
Create Date: 2016-11-14 13:24:05.417718

"""

# revision identifiers, used by Alembic.
revision = '037db101b7d5'
down_revision = 'c720167ec7a8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'party', ['code'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'party', type_='unique')
    ### end Alembic commands ###
