"""empty message

Revision ID: c720167ec7a8
Revises: None
Create Date: 2016-11-13 17:39:48.891673

"""

# revision identifiers, used by Alembic.
revision = 'c720167ec7a8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('canonical', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('canonical'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('url')
    )
    op.create_table('party',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('colour', sa.String(length=10), nullable=False),
    sa.Column('text_colour', sa.String(length=10), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('candidate', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('url')
    )
    op.create_table('poll',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('client', sa.String(length=100), nullable=True),
    sa.Column('company_code', sa.String(length=6), nullable=True),
    sa.ForeignKeyConstraint(['company_code'], ['company.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poll_party',
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('party_code', sa.String(length=10), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['party_code'], ['party.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('poll_id', 'party_code')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poll_party')
    op.drop_table('poll')
    op.drop_table('party')
    op.drop_table('company')
    ### end Alembic commands ###
